language: php
sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

jobs:
  fast_finish: true
  allow_failures:
    - php: "nightly"
  include:
    - php: "7.1"
    - php: "7.2"
    - php: "7.3"
    - php: "7.4"
    - php: "nightly"

install:
  - composer install

# vim:ts=2:sw=2:et
